/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32h7xx.h>
#include <stdint.h>
#include <math.h>

#include <board.h>
#include <board_functions.h>
#include <LCD_out.h>
#include <LCD_draw_lib.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)  // make sure fp ops available
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t tubespace;

#define BLACK  		   0x0000
#define RED  	       0xF800
#define MNIGHTBLUE     0x4000
#define GREEN  		   0x07E0
#define YELLOW  	   0x07FF
#define MAGENTA 	   0xF81F
#define CYAN   	 	   0xFFE0
#define WHITE 		   0xFFFF
#define GREEN2 		   0x2FA4
#define CYAN2 		   0x07FF
#define BLUE  		   0xFA20

#define LCD_hight      239
#define LCD_with       319




uint8_t tubespace;


typedef struct {  //typedef to call struct by gappos
    uint8_t gaplow;  // vall
    uint8_t gaphigh;     // valh
} gappos;
















gappos tuberand(void){  // call RNG to work;    create 2 rand vals with def space inbetw
//min !must! be in range of LCD hight = 0 to (240 - 1)
	uint8_t tubespace = 50;                    // 50 px betw tubes  -> make smaller by time passed
                                           //
	uint32_t val = RandomNG();            //                                                                ____________________________________
    //                  max    min + 1     //                                                                \                 /                |
	uint8_t vall = (val % (LCD_hight - tubespace + 1));   // shrink val to LCD writeable space  vall % 190 ->  (2^32 - 1) - {[(2^32 - 1) / 190] - residual of} * 190 - 50  = (0,...,239)
	uint8_t valh = vall + tubespace;


	gappos result;               // result has same type as gappos
	    result.gaplow = vall;    // save vall in gaplow var of struct "result"
	    result.gaphigh = valh;   // save valh in gaphigh var of struct "result"

	    return result;           // return struct "result" -> needs to be saved in struct "gappos" or other struct of same type as gappos


}







int main() {
    DWT_Init();
    board_voltage();
	board_oclk(1);
	board_start();
    LCD_Init();
    delay(1000);

	for(;;){
			Line(320,0,90, MAGENTA);//}
			Line(320,150,240, GREEN);//}
			Line(305,0,90,BLUE);
			Line(305,150,239,YELLOW);
			delay(10);
			scr_area(0,320,0);
	//int a;

			for(int i = 0;i < LCD_with + 1; i++){
				LCD_Scroll(i + 1);
				delay_u(3000);
				Line(i,0,240,MNIGHTBLUE);//}
				if((i % 40 == 0) && (i < 320)){
					//a = i * 40 - 1;
					gappos gappos = tuberand();
					Line(i,0,gappos.gaplow, 204 * i);//
					Line(i,gappos.gaphigh,239, 204 * i);//
				}

			//	RNG p. 1405 RM_________________________________________________________________________________

				if(i == 319){i = 0;}
			}

	}


}
