/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32h7xx.h>
#include <stdint.h>
#include <math.h>

#include <board.h>
#include <board_functions.h>
#include <LCD_out.h>
#include <LCD_draw_lib.h>






#if !defined(__SOFT_FP__) && defined(__ARM_FP)  // make sure fp ops available
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#define BLACK   0x0000
#define RED     0xF800
#define RED2    0x4000
#define GREEN   0x07E0
#define YELLOW  0x07FF
#define MAGENTA 0xF81F
#define CYAN    0xFFE0
#define WHITE   0xFFFF
#define GREEN2  0x2FA4
#define CYAN2   0x07FF
#define BLUE    0xFA20





int main() {
    DWT_Init();
    board_voltage();
	board_oclk(1);
	board_start();
    LCD_Init();
    delay(1000);


	//Rect(0,320,0,240,BLACK);
	delay(100);
	for(;;){
			Line(320,0,90, MAGENTA);//}
			Line(320,150,240, GREEN);//}
			Line(305,0,90,BLUE);
			Line(305,150,240,YELLOW);
			delay(10);
			scr_area(0,320,0);
	//int a;

			for(int i = 0;i <= 319; i++){
				LCD_Scroll(i + 1);
				//delay_u(30);
				Line(i,0,240,RED2);//}
				if(i % 40 == 0){
					//a = i * 40 - 1;
					Line(i,0,90, 204 * i);//
					Line(i,150,240, 204 * i);//
				}

			//	RNG p. 1405 RM_________________________________________________________________________________

				if(i == 319){i = 0;}
			}

	}


}
